apiVersion: v1

kind: Pod

metadata:
  name: db
  labels:
    name: db
    app: voting-app

spec:
  containers:
    - name: db
      image: postgres
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust" # anyone can connect with DB without password